#source 'https://github.com/CocoaPods/Specs.git'        #官方仓库地址
#source 'https://github.com/chengshiliang/Sqlite-master.git'        #私有仓库地址

target 'JKDBModel' do
pod 'SqliteLibrary', :path => '../'
end
